// @ts-check

// 此代码在 Node.js 中运行 - 请勿在此处使用客户端代码（浏览器 API、JSX...）

/**
 * 创建侧边栏可以让你：
 - 创建有序的文档组
 - 为该组中的每个文档渲染侧边栏
 - 提供上一篇/下一篇导航

 侧边栏可以从文件系统生成，也可以在此处显式定义。

 根据需要创建任意数量的侧边栏。

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 手动创建侧边栏配置
  tutorialSidebar: [
    // 主页介绍
    'intro',

    // 前端开发相关
    {
      type: 'category',
      label: '📚 前端笔记',
      items: [
        '前端笔记/create-a-document',    // 创建文档
        '前端笔记/create-a-page',        // 创建页面
        '前端笔记/create-a-blog-post',   // 创建博客
        '前端笔记/deploy-your-site',     // 部署站点
      ],
    },

    // Docker 教程
    {
      type: 'category',
      label: '🐳 Docker 教程',
      items: [
        // 基本使用分类
        {
          type: 'category',
          label: '📖 基本使用',
          items: [
            'Docker/basic-usage/install-docker',  // Docker 安装教程
          ],
        },
        // 进阶教程分类
        {
          type: 'category',
          label: '⚙️ 进阶教程',
          items: [
            'Docker/create-a-blog-post',     // Dockerfile 编写
            // 可以在这里添加更多进阶内容
          ],
        },
        // 学习完成
        'Docker/congratulations',        // Docker 学习完成
      ],
    },

    // 完成指南
    '前端笔记/congratulations',
  ],

};

export default sidebars;
